server:
  port: 9050
  servlet.context-path: /account

spring:
  datasource:
    url: jdbc:postgresql://localhost:9010/lovable-account-db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

stripe:
  secretKey: sk_test_51SuXtRPWB6wRPLw73NOsMzCKTydGglSJKad0sLGYsbKrmk3bSCk93AYs4riHTcSh08yHxzwN6od8gVMmz901LeHh008Vdo3iQc
webhook:
  secret: whsec_87b0cdeeff180676bc2b04a8dd33d7b1f9e4975c049271b16b9f506fbf252ca4
