server:
  port: 9030
  servlet:
    context-path: /intelligence

spring:
  datasource:
    url: jdbc:postgresql://localhost:9010/lovable-intelligence-db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  ai:
    openai:
      api-key: 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
      base-url: https://api.openai.com
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.2

logging:
  level:
    com.sarm.distributed_lovable: DEBUG
    org.springframework.ai: DEBUG
 
          

      
