server:
  port: 9030
  servlet:
    context-path: /intelligence

spring:
  datasource:
    url: jdbc:postgresql://localhost:9010/lovable-intelligence-db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  ai:
    openai:
      api-key: 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
      base-url: https://api.openai.com/v1
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.2

logging:
  level:
    com.sarm.distributed_lovable: DEBUG
    org.springframework.ai: DEBUG
 
          

      
